### PR TITLE
use a non-root user inside the Docker container

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f29cc52 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f29cc52 with merge f29cc52...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/trust/builds/163853688)
Approved by: japaric
Pushing f29cc521aaf84372f7bdee675189bc3e32da870b to master...

**Pull request merged**
