### PR TITLE
test armhf

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8d0ce7f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8d0ce7f with merge 8d0ce7f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163614906)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 296219b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 296219b with merge 296219b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163616800)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9481f75 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9481f75 with merge 9481f75...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163617587)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6185f6a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6185f6a with merge 6185f6a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/trust/builds/163775510)
Approved by: japaric
Pushing 6185f6a3bd4fe7dac00758255d0f38da97479725 to master...

**Pull request merged**
