### PR TITLE
switch to git gcc-rs to fix the i586-msvc build

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ccfe4fc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ccfe4fc with merge ccfe4fc...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.39), [status-travis](https://travis-ci.org/japaric/trust/builds/168112425)
Approved by: japaric
Pushing ccfe4fc2988886db0657fd2395936383f23b0611 to master...

**Pull request merged**
