### PR TITLE
fix deploys for thumb targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aa05f8d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aa05f8d with merge aa05f8d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/168172358)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.47), [status-travis](https://travis-ci.org/japaric/trust/builds/168172446)
Approved by: japaric
Pushing aa05f8d9ed65dce1f16a5cf57909c0e0639524b3 to master...

**Pull request merged**
