### PR TITLE
initial appveyor configuration

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit a696180 with merge a696180...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.3)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit eafc278 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit eafc278 with merge eafc278...

**Comment by japaric** [comment]
Tests passed.

**Pull request merged**
