### PR TITLE
drop Docker files, use `cross`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit ae587ca with merge ae587ca...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.55), [status-travis](https://travis-ci.org/japaric/trust/builds/186856451)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 0dcbdf5 with merge 0dcbdf5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/187304184)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit be02139 with merge be02139...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.60)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.57), [status-travis](https://travis-ci.org/japaric/trust/builds/187308271)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1cd3f3e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1cd3f3e with merge 1cd3f3e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.61)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.58), [status-travis](https://travis-ci.org/japaric/trust/builds/187336042)
Approved by: japaric
Pushing 1cd3f3e7dc8084153c0ff6dd6e17a1e53846ddd2 to master...

**Pull request merged**
