### PR TITLE
Run Travis builds for all branches & PRs

### PR DESCRIPTION
**Pull request by slonopotamus**

### CODE REVIEW

**Comment by slonopotamus** [comment]
Hmm, this doesn't work =/

**Comment by Dylan-DPC** [comment]
@slonopotamus Hi. Thanks for informing us about this. Will check it in a while and fix it.

**Comment by slonopotamus** [comment]
So, not running Travis for PRs is not intentional?

**Comment by slonopotamus** [comment]
Check an option "Build pushed pull requests" in [Travis repository settings](https://travis-ci.org/japaric/trust/settings). Is it enabled?

**Comment by slonopotamus** [comment]
Yeah, I think that is the problem. See [Travis PR log](https://travis-ci.org/japaric/trust/requests):
```Build type disabled via repository settings (pull_request).```

**Comment by Dylan-DPC** [comment]
Yeah thanks I have enabled it now.

**Pull request closed without merging**
