### PR TITLE
during deploy, non-deploy branches should NOP

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 582e022 with merge 582e022...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.36), [status-travis](https://travis-ci.org/japaric/trust/builds/168070804)
State: approved= try=True

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.33), [status-travis](https://travis-ci.org/japaric/trust/builds/168070804)
State: approved= try=True

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.33), [status-travis](https://travis-ci.org/japaric/trust/builds/168078021)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fcd65aa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fcd65aa with merge fcd65aa...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.35), [status-travis](https://travis-ci.org/japaric/trust/builds/168084853)
Approved by: japaric
Pushing fcd65aab5ec32c44b98b5610fa60bbe2d5f92c2e to master...

**Pull request merged**
