### PR TITLE
test the thumb targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e4fa0f6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e4fa0f6 with merge 92efffd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.38), [status-travis](https://travis-ci.org/japaric/trust/builds/168156602)
Approved by: japaric
Pushing 92efffdedd81eb10842b9b45e4faffa9a8449254 to master...

**Pull request merged**
