### PR TITLE
test the new targets that came up today

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 3c55c74 with merge 3c55c74...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bangbang: Invalid head SHA found, retrying: `0000000000000000000000000000000000000000`

**Comment by homunkulus** [comment]
:pushpin: Commit 3c55c74 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3c55c74 with merge 35235db...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit d48dad5 with merge 2e1efe8...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/167776123)

**Pull request merged**
