### PR TITLE
test osx and 32-bit linux

### LINKED ISSUE #2: OSX

### PR DESCRIPTION
**Pull request by japaric**
closes #2

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 41bea38 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 41bea38 with merge 41bea38...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fe25483 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fe25483 with merge fe25483...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ce7edfc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ce7edfc with merge ce7edfc...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 26698bb with merge 26698bb...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163864549)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit b18afbe with merge b18afbe...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163866573)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7a8039b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7a8039b with merge 7a8039b...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7b9f2ed has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7b9f2ed with merge 7b9f2ed...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/trust/builds/163869202)
Approved by: japaric
Pushing 7b9f2ed1d3d215f7b1d2c27e0edf852b68dddb58 to master...

**Pull request merged**
