### PR TITLE
ci: tweak the trigger logic

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c9081df has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c9081df with merge c9081df...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/185671090)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1f19aae has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1f19aae with merge 1f19aae...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/185764044)

**Pull request merged**
