### PR TITLE
remove the install.sh script from the master branch

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 02cc5db has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 02cc5db with merge 02cc5db...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.53)

**Pull request merged**
