### PR TITLE
ci/install.sh: stick to the v0.1.x version series of Cross

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1c8164e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1c8164e with merge 1c8164e...

**Comment by japaric** [comment]
The tests passed. Merging manually.

**Pull request merged**
