### PR TITLE
remove webhook

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5b4867a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5b4867a with merge 5b4867a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.45)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5b4867a with merge 5b4867a...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 48d96c5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 48d96c5 with merge 48d96c5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.46)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aa259ec has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aa259ec with merge aa259ec...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/174113051)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 90a5883 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 90a5883 with merge 90a5883...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/175194232)

**Pull request merged**
