### PR TITLE
test more targets

### PR DESCRIPTION
**Pull request by japaric**
fix permissions

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b36ca1e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b36ca1e with merge b36ca1e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163894590)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit b36ca1e with merge b36ca1e...

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Trying commit b36ca1e with merge b36ca1e...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request is currently being tested. If there's no response from the continuous integration service, you may use `retry` to trigger a build again.

**Comment by homunkulus** [comment]
:pushpin: Commit b36ca1e has been approved by `japaric`

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163897204)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit b36ca1e with merge b36ca1e...

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit b36ca1e with merge b36ca1e...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0944730 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0944730 with merge 0944730...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163991489)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0944730 with merge 0944730...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1758522 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1758522 with merge 1758522...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/164093181)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ab5867f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ab5867f with merge ab5867f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/164198600)

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 256d168 with merge 256d168...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/165403183)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit fa34120 with merge fa34120...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/165424624)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5cdb5d5 with merge 5cdb5d5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/165425689)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 80fc0a4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 80fc0a4 with merge 80fc0a4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/trust/builds/165427150)
Approved by: japaric
Pushing 80fc0a4fd1f9cff954bdcad859cfb10c9131dd9a to master...

**Pull request merged**
