### PR TITLE
Drop need for SUDO for faster Travis scheduling

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
Well it seems the `sudo` setting is set by TravisCI from the `services: docker` thing.
I can either
1. revert last commit and squash
1. close this PR

you decide :)

**Comment by japaric** [comment]
Can you do `sudo apt-get ..` if you drop `sudo: required`? I have a vague recollection of trying something like that and that `sudo` couldn't be used. I may be misremembering though.

**Comment by fenollp** [comment]
Ah you're saying this works because the cache saves the day?
In any case since this PR doesn't seem to make the jobs run on the Travis Docker workers, it can be closed.
But maybe they do run on the docker workers? I'm not sure.

**Comment by japaric** [comment]
> In any case since this PR doesn't seem to make the jobs run on the Travis Docker workers, it can be closed

OK. Let's better leave this as it is then.

**Pull request closed without merging**
