### PR TITLE
Improve comment on "build: false" for appveyor

### LINKED ISSUE #58: More descriptive comment on build: false
This part of `appveyor.yml` is not easy to understand for someone not very familiar with Appveyor:

```yml
# disable automatic builds
build: false
```

It sounds like it turns off automatically building new commits to the project. Which it doesn't.

If the following comment is correct I would say it describes the setting in a clearer way:
```yml
# We build in the test stage, so disable Appveyor's build stage.
build: false
```

### PR DESCRIPTION
**Pull request by faern**
Fixes #58

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @faern!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d8303b9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d8303b9 with merge d8303b9...

**Comment by homunkulus** [comment]
:boom: Test timed out

**Comment by japaric** [comment]
Tests passed. Merging manually.

**Pull request merged**
