### PR TITLE
add musl target and test compiling C code

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6b46469 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6b46469 with merge 48d6d46...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163827969)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit dc683b6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit dc683b6 with merge dc683b6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163841881)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 853c88d with merge 853c88d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163843463)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5f80105 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5f80105 with merge 5f80105...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163845644)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9660cce has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9660cce with merge 9660cce...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/trust/builds/163847862)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a0e035e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a0e035e with merge a0e035e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/trust/builds/163848942)
Approved by: japaric
Pushing a0e035ea27bc91be715f9f84a8f033ce7af55c94 to master...

**Pull request merged**
