### PR TITLE
fetch trust/install.sh using HTTPS

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 091fa57 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 091fa57 with merge 091fa57...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.52)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f33da60 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f33da60 with merge 6ee8081...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.51), [status-travis](https://travis-ci.org/japaric/trust/builds/175365274)
Approved by: japaric
Pushing 6ee80811386dd1f55c1103cb52a8e5c960236c8a to master...

**Pull request merged**
