### PR TITLE
enable the powerpc targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit d910340 with merge d910340...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8ddc7e1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8ddc7e1 with merge 8ddc7e1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.6), [status-travis](https://travis-ci.org/japaric/trust/builds/167554525)
Approved by: japaric
Pushing 8ddc7e12ca78eea987aaa58ab0e3964f10ccf04b to master...

**Pull request merged**
