### PR TITLE
docker: merge apt-get update and apt-get install

### PR DESCRIPTION
**Pull request by japaric**
to avoid 404 errors due to Docker image caching

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 19948be has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 19948be with merge 19948be...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.55), [status-travis](https://travis-ci.org/japaric/trust/builds/175389922)
Approved by: japaric
Pushing 19948befcf19777d587bd450c6362bf570a3a73c to master...

**Pull request merged**
