### PR TITLE
Travis: propagate failures

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 4e145ba with merge 4e145ba...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit dec1b00 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit dec1b00 with merge dec1b00...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/trust/build/1.0.44), [status-travis](https://travis-ci.org/japaric/trust/builds/168164243)
Approved by: japaric
Pushing dec1b008e45fe665bcdc03000282ae55181fe673 to master...

**Pull request merged**
